apiVersion: v1
kind: Namespace
metadata:
  name: hackademy-k8s
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: hackademy-k8s
type: Opaque
stringData:
  mysql-root-password: asd777